; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATtiny412]
platform = atmelmegaavr
board = ATtiny412
framework = arduino
upload_protocol = serialupdi

; change MCU frequency
board_build.f_cpu = 1000000L

monitor_speed = 57600

[env:ATtiny416]
platform = atmelmegaavr
board = ATtiny416
framework = arduino
upload_protocol = serialupdi

; change MCU frequency
board_build.f_cpu = 1000000L

monitor_speed = 57600

; run the following command to set fuses
; pio run -t fuses -e set_fuses
[env:set_fuses]
platform = atmelmegaavr
board = ATtiny412
framework = arduino
board_build.f_cpu = 1000000L
; Upload protocol for used to set fuses
upload_protocol = serialupdi
upload_flags =
; Hardware settings
board_hardware.bod = 1.8v